version: "3.8"
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/ecotionbuddy}
      - MQTT_HOST=${MQTT_HOST:-mqtt}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - IMAGE_STORAGE=${IMAGE_STORAGE:-disk}
      - UPLOADS_DIR=${UPLOADS_DIR:-uploads}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}
      - MIRROR_SHARE_PATH=${MIRROR_SHARE_PATH:-}
    depends_on:
      - mqtt
      - mongo
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./model:/app/model

volumes:
  mongo_data:
